package neo.bank.cliente.domain.models.enums;

public enum CodiceErrore {
    

    ID_NON_VALIDO("ID_NON_VALIDO"),
    CODICE_CLIENTE_NON_VALIDO("CODICE_CLIENTE_NON_VALIDO"),
    NOME_CLIENTE_NON_VALIDO("NOME_CLIENTE_NON_VALIDO"),
    COGNOME_CLIENTE_NON_VALIDO("COGNOME_CLIENTE_NON_VALIDO"),
    USERNAME_CLIENTE_NON_PUO_ESSERE_NULL("USERNAME_CLIENTE_NON_PUO_ESSERE_NULL"),
    CODICE_FISCALE_NON_VALIDO("CODICE_FISCALE_NON_VALIDO"),
    TELEFONO_NON_VALIDO("TELEFONO_NON_VALIDO"),
    EMAIL_NON_VALIDA("EMAIL_NON_VALIDA"),
    DATA_NASCITA_NON_PUO_ESSERE_NULL("DATA_NASCITA_NON_PUO_ESSERE_NULL"),
    CLIENTE_DEVE_ESSERE_MAGGIORENNE("CLIENTE_DEVE_ESSERE_MAGGIORENNE"),
    RESIDENZA_NON_VALIDA("RESIDENZA_NON_VALIDA"),
    CODICE_SWIFT_NON_PUO_ESSERE_NULL("CODICE_SWIFT_NON_PUO_ESSERE_NULL"),
    SOGLIA_BONIFICO_MENSILE_MINORE_UGUALE_ZERO("SOGLIA_BONIFICO_MENSILE_MINORE_UGUALE_ZERO"),
    SOGLIA_BONIFICO_GIORNALIERA_MINORE_UGUALE_ZERO("SOGLIA_BONIFICO_GIORNALIERA_MINORE_UGUALE_ZERO"),
    SOGLIE_BONIFICO_NON_VALIDE_NON_COERERENTI("SOGLIE_BONIFICO_NON_VALIDE_NON_COERERENTI"),
    CODICE_ABI_NON_PUO_ESSERE_NULL("CODICE_ABI_NON_PUO_ESSERE_NULL"),
    CODICE_CAB_NON_PUO_ESSERE_NULL("CODICE_CAB_NON_PUO_ESSERE_NULL"),
    DATA_APERTURA_NON_PUO_ESSERE_NULL("DATA_APERTURA_NON_PUO_ESSERE_NULL"),
    DATA_CHIUSURA_NON_PUO_ESSERE_NULL("DATA_CHIUSURA_NON_PUO_ESSERE_NULL"),
    IBAN_NON_PUO_ESSERE_NULL("IBAN_NON_PUO_ESSERE_NULL");

    private String codice;

    private CodiceErrore(String codice) {
        this.codice = codice;
    }

    public String getCodice() {
        return codice;
    }
    
    
}
